//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.5872.26164
// Compatible with MoonSharp v.1.2.99.0 or equivalent
// ----------------------------------------------------------
// Code generated on 2016-01-29T14:32:12.7535057+01:00
// ----------------------------------------------------------
// 
// 
// 
namespace MyNamespace
{


	public abstract class MyClass
	{

		private MyClass()
		{
		}

		public static void Initialize()
		{
			//MoonSharp.Interpreter.UserData.Register(new HardwiredDescriptor_MoonSharp_Interpreter_Interop_AnonWrapper());
			//MoonSharp.Interpreter.UserData.Register(new HardwiredDescriptor_MoonSharp_Interpreter_Script());
		}

		private sealed class HardwiredDescriptor_MoonSharp_Interpreter_Interop_AnonWrapper : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor
		{

			internal HardwiredDescriptor_MoonSharp_Interpreter_Interop_AnonWrapper() :
				base(typeof(MoonSharp.Interpreter.Interop.AnonWrapper))
			{
			}
		}

		private sealed class HardwiredDescriptor_MoonSharp_Interpreter_Script : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor
		{

			internal HardwiredDescriptor_MoonSharp_Interpreter_Script() :
				base(typeof(MoonSharp.Interpreter.Script))
			{
				this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_8a1dc64a338648d3bfb2646fb0dd0f9b(),
                                new M_12b741850138417cacb8f17860c252da()}));
				this.AddMember("get_DefaultOptions", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_DefaultOptions", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_a59a07aeaab747b9bd587892f08ee962()}));
				this.AddMember("get_Options", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Options", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_6f183c6e798541caa4693c8cdfbe8335()}));
				this.AddMember("get_GlobalOptions", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_GlobalOptions", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_7781d7722c984a4182968ddb7c457b4e()}));
				this.AddMember("get_PerformanceStats", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_PerformanceStats", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_25d1541f1ffe4225ba4b3c43722e1183()}));
				this.AddMember("get_Globals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Globals", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_379e6d1e62bf4a15b4e67c792341fcfe()}));
				this.AddMember("LoadFunction", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("LoadFunction", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_72c2f70386a34ddf91cc0827597b6bad()}));
				this.AddMember("LoadString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("LoadString", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_c2a85944914f48f6a0cb03e3dd46f8b4()}));
				this.AddMember("LoadStream", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("LoadStream", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_7338a36baaec4b5890dc006a3b094708()}));
				this.AddMember("Dump", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Dump", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_f27ef9d210184d4397392d7db9e463e1()}));
				this.AddMember("LoadFile", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("LoadFile", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_265c5d8d70b84072812f7e03a4889705()}));
				this.AddMember("DoString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("DoString", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_439c401f09e7492c840972599f11def7()}));
				this.AddMember("DoStream", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("DoStream", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_8e4253a3a91f487ab958e052d173414d()}));
				this.AddMember("DoFile", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("DoFile", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_82bbedfac3aa47efa49310773cf3c48f()}));
				this.AddMember("RunFile", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("RunFile", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_81203eee1e4241319ecfbc9435a7ef1f()}));
				this.AddMember("RunString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("RunString", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_b890a53ae6d04f6d8a8a4e8d93f1bd95()}));
				this.AddMember("Call", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Call", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_60c1310f6a6c46439e9ecb6c969f0492(),
                                new M_21f4d437f5d04705a0db881cff40ed57(),
                                new M_563c0b7b43614f7f8f57dcc5e4490d61(),
                                new M_80478408177a425fab2c9e16c40f21ec(),
                                new M_874665ac6c564c56ad50eb7e7028a855()}));
				this.AddMember("CreateCoroutine", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("CreateCoroutine", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_01b369d9ba0d409f879677700902d562(),
                                new M_54f580c9a9fc4665923c07ba301bd498()}));
				this.AddMember("GetMainChunk", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetMainChunk", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_c004ce403184416e975ef1ac664b89c0()}));
				this.AddMember("get_DebuggerEnabled", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_DebuggerEnabled", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_2582ec6dedd7466e8e2fdaecc951c77e()}));
				this.AddMember("set_DebuggerEnabled", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("set_DebuggerEnabled", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_26973cf676c64057bb4c625490ca3ad7()}));
				this.AddMember("AttachDebugger", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("AttachDebugger", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_e9b565c0909843558196cf9dfed68c9d()}));
				this.AddMember("GetSourceCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetSourceCode", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_0503acc40e474a9e9f0b2afb3a651404()}));
				this.AddMember("get_SourceCodeCount", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_SourceCodeCount", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_bff6753629d14b269638e3068780666f()}));
				this.AddMember("RequireModule", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("RequireModule", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_0cf157087a2148b9be38756d5eacc076()}));
				this.AddMember("GetTypeMetatable", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetTypeMetatable", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_e87066ffa4d2410884648dfd8b48ea0e()}));
				this.AddMember("SetTypeMetatable", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("SetTypeMetatable", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_cbb3b3b05859416bbed10068731597e3()}));
				this.AddMember("WarmUp", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("WarmUp", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_6b129f8f58e5472bbaf37f351859b4d5()}));
				this.AddMember("CreateDynamicExpression", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("CreateDynamicExpression", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_8922d4f9487e4ec3849188d8ffaa8a9c()}));
				this.AddMember("CreateConstantDynamicExpression", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("CreateConstantDynamicExpression", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_43ab32ba0bf84865a409a098d73c5ae9()}));
				this.AddMember("get_Registry", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Registry", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_516a8a4cd0ac4f359001d999182bb2e8()}));
				this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_904e48f68ae640eaae4b4b57dfd815f5()}));
				this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_c73c2a427b2544ffa000ff0b84363b9b()}));
				this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_dba924bc2bc24f2cb9100c5354566c95()}));
				this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(MoonSharp.Interpreter.Script), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new M_71ba8a4297a94bd9bf3cbe05cd4a6b09()}));
				this.AddMember("DefaultOptions", new P_b8b9640e05c5462cb3bc5a0715c8ead5());
				this.AddMember("Options", new P_c7ddbdc1d468476381392c0962390924());
				this.AddMember("GlobalOptions", new P_45a1cf5169904bf690a200d6ccfdd64c());
				this.AddMember("PerformanceStats", new P_845a56b2b70e4e3aa780dc2c28679d9c());
				this.AddMember("Globals", new P_9004ba7d477746bfa582d82b5c88b282());
				this.AddMember("DebuggerEnabled", new P_762a7898cbab4404871937e06970317a());
				this.AddMember("SourceCodeCount", new P_ec50dada3aa94231bd511c7a7679e136());
				this.AddMember("Registry", new P_3327f505764b45aab1705dba88e499d5());
				this.AddMember("VERSION", new F_1da771af519647b9a55aea146eabf20b());
				this.AddMember("LUA_VERSION", new F_c9b0fd6485c7431e8bb808039f675d6e());
			}

			private sealed class M_8a1dc64a338648d3bfb2646fb0dd0f9b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_8a1dc64a338648d3bfb2646fb0dd0f9b()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new MoonSharp.Interpreter.Script();
				}
			}

			private sealed class M_12b741850138417cacb8f17860c252da : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_12b741850138417cacb8f17860c252da()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("coreModules", typeof(MoonSharp.Interpreter.CoreModules), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new MoonSharp.Interpreter.Script(((MoonSharp.Interpreter.CoreModules)(pars[0])));
				}
			}

			private sealed class M_a59a07aeaab747b9bd587892f08ee962 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_a59a07aeaab747b9bd587892f08ee962()
				{
					this.Initialize("get_DefaultOptions", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return MoonSharp.Interpreter.Script.DefaultOptions;
				}
			}

			private sealed class M_6f183c6e798541caa4693c8cdfbe8335 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_6f183c6e798541caa4693c8cdfbe8335()
				{
					this.Initialize("get_Options", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Options;
				}
			}

			private sealed class M_7781d7722c984a4182968ddb7c457b4e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_7781d7722c984a4182968ddb7c457b4e()
				{
					this.Initialize("get_GlobalOptions", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return MoonSharp.Interpreter.Script.GlobalOptions;
				}
			}

			private sealed class M_25d1541f1ffe4225ba4b3c43722e1183 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_25d1541f1ffe4225ba4b3c43722e1183()
				{
					this.Initialize("get_PerformanceStats", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).PerformanceStats;
				}
			}

			private sealed class M_379e6d1e62bf4a15b4e67c792341fcfe : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_379e6d1e62bf4a15b4e67c792341fcfe()
				{
					this.Initialize("get_Globals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Globals;
				}
			}

			private sealed class M_72c2f70386a34ddf91cc0827597b6bad : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_72c2f70386a34ddf91cc0827597b6bad()
				{
					this.Initialize("LoadFunction", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalTable", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("funcFriendlyName", typeof(string), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadFunction(((string)(pars[0])));
					}
					if ((argscount <= 2))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadFunction(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).LoadFunction(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])), ((string)(pars[2])));
				}
			}

			private sealed class M_c2a85944914f48f6a0cb03e3dd46f8b4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_c2a85944914f48f6a0cb03e3dd46f8b4()
				{
					this.Initialize("LoadString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalTable", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("codeFriendlyName", typeof(string), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadString(((string)(pars[0])));
					}
					if ((argscount <= 2))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadString(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).LoadString(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])), ((string)(pars[2])));
				}
			}

			private sealed class M_7338a36baaec4b5890dc006a3b094708 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_7338a36baaec4b5890dc006a3b094708()
				{
					this.Initialize("LoadStream", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("stream", typeof(System.IO.Stream), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalTable", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("codeFriendlyName", typeof(string), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadStream(((System.IO.Stream)(pars[0])));
					}
					if ((argscount <= 2))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadStream(((System.IO.Stream)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).LoadStream(((System.IO.Stream)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])), ((string)(pars[2])));
				}
			}

			private sealed class M_f27ef9d210184d4397392d7db9e463e1 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_f27ef9d210184d4397392d7db9e463e1()
				{
					this.Initialize("Dump", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("stream", typeof(System.IO.Stream), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					((MoonSharp.Interpreter.Script)(obj)).Dump(((MoonSharp.Interpreter.DynValue)(pars[0])), ((System.IO.Stream)(pars[1])));
					return null;
				}
			}

			private sealed class M_265c5d8d70b84072812f7e03a4889705 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_265c5d8d70b84072812f7e03a4889705()
				{
					this.Initialize("LoadFile", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("filename", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalContext", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("friendlyFilename", typeof(string), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadFile(((string)(pars[0])));
					}
					if ((argscount <= 2))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).LoadFile(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).LoadFile(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])), ((string)(pars[2])));
				}
			}

			private sealed class M_439c401f09e7492c840972599f11def7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_439c401f09e7492c840972599f11def7()
				{
					this.Initialize("DoString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalContext", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).DoString(((string)(pars[0])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).DoString(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
				}
			}

			private sealed class M_8e4253a3a91f487ab958e052d173414d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_8e4253a3a91f487ab958e052d173414d()
				{
					this.Initialize("DoStream", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("stream", typeof(System.IO.Stream), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalContext", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).DoStream(((System.IO.Stream)(pars[0])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).DoStream(((System.IO.Stream)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
				}
			}

			private sealed class M_82bbedfac3aa47efa49310773cf3c48f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_82bbedfac3aa47efa49310773cf3c48f()
				{
					this.Initialize("DoFile", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("filename", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalContext", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).DoFile(((string)(pars[0])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).DoFile(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
				}
			}

			private sealed class M_81203eee1e4241319ecfbc9435a7ef1f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_81203eee1e4241319ecfbc9435a7ef1f()
				{
					this.Initialize("RunFile", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("filename", typeof(string), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return MoonSharp.Interpreter.Script.RunFile(((string)(pars[0])));
				}
			}

			private sealed class M_b890a53ae6d04f6d8a8a4e8d93f1bd95 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_b890a53ae6d04f6d8a8a4e8d93f1bd95()
				{
					this.Initialize("RunString", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return MoonSharp.Interpreter.Script.RunString(((string)(pars[0])));
				}
			}

			private sealed class M_60c1310f6a6c46439e9ecb6c969f0492 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_60c1310f6a6c46439e9ecb6c969f0492()
				{
					this.Initialize("Call", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Call(((MoonSharp.Interpreter.DynValue)(pars[0])));
				}
			}

			private sealed class M_21f4d437f5d04705a0db881cff40ed57 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_21f4d437f5d04705a0db881cff40ed57()
				{
					this.Initialize("Call", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("args", typeof(MoonSharp.Interpreter.DynValue[]), false, null, false, false, true)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Call(((MoonSharp.Interpreter.DynValue)(pars[0])), ((MoonSharp.Interpreter.DynValue[])(pars[1])));
				}
			}

			private sealed class M_563c0b7b43614f7f8f57dcc5e4490d61 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_563c0b7b43614f7f8f57dcc5e4490d61()
				{
					this.Initialize("Call", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("args", typeof(object[]), false, null, false, false, true)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Call(((MoonSharp.Interpreter.DynValue)(pars[0])), ((object[])(pars[1])));
				}
			}

			private sealed class M_80478408177a425fab2c9e16c40f21ec : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_80478408177a425fab2c9e16c40f21ec()
				{
					this.Initialize("Call", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(object), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Call(((object)(pars[0])));
				}
			}

			private sealed class M_874665ac6c564c56ad50eb7e7028a855 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_874665ac6c564c56ad50eb7e7028a855()
				{
					this.Initialize("Call", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(object), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("args", typeof(object[]), false, null, false, false, true)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Call(((object)(pars[0])), ((object[])(pars[1])));
				}
			}

			private sealed class M_01b369d9ba0d409f879677700902d562 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_01b369d9ba0d409f879677700902d562()
				{
					this.Initialize("CreateCoroutine", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).CreateCoroutine(((MoonSharp.Interpreter.DynValue)(pars[0])));
				}
			}

			private sealed class M_54f580c9a9fc4665923c07ba301bd498 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_54f580c9a9fc4665923c07ba301bd498()
				{
					this.Initialize("CreateCoroutine", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("function", typeof(object), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).CreateCoroutine(((object)(pars[0])));
				}
			}

			private sealed class M_c004ce403184416e975ef1ac664b89c0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_c004ce403184416e975ef1ac664b89c0()
				{
					this.Initialize("GetMainChunk", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).GetMainChunk();
				}
			}

			private sealed class M_2582ec6dedd7466e8e2fdaecc951c77e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_2582ec6dedd7466e8e2fdaecc951c77e()
				{
					this.Initialize("get_DebuggerEnabled", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).DebuggerEnabled;
				}
			}

			private sealed class M_26973cf676c64057bb4c625490ca3ad7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_26973cf676c64057bb4c625490ca3ad7()
				{
					this.Initialize("set_DebuggerEnabled", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(bool), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					((MoonSharp.Interpreter.Script)(obj)).DebuggerEnabled = ((bool)(pars[0]));
					return null;
				}
			}

			private sealed class M_e9b565c0909843558196cf9dfed68c9d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_e9b565c0909843558196cf9dfed68c9d()
				{
					this.Initialize("AttachDebugger", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("debugger", typeof(MoonSharp.Interpreter.Debugging.IDebugger), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					((MoonSharp.Interpreter.Script)(obj)).AttachDebugger(((MoonSharp.Interpreter.Debugging.IDebugger)(pars[0])));
					return null;
				}
			}

			private sealed class M_0503acc40e474a9e9f0b2afb3a651404 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_0503acc40e474a9e9f0b2afb3a651404()
				{
					this.Initialize("GetSourceCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("sourceCodeID", typeof(int), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).GetSourceCode(((int)(pars[0])));
				}
			}

			private sealed class M_bff6753629d14b269638e3068780666f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_bff6753629d14b269638e3068780666f()
				{
					this.Initialize("get_SourceCodeCount", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).SourceCodeCount;
				}
			}

			private sealed class M_0cf157087a2148b9be38756d5eacc076 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_0cf157087a2148b9be38756d5eacc076()
				{
					this.Initialize("RequireModule", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("modname", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("globalContext", typeof(MoonSharp.Interpreter.Table), true, new MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.DefaultValue(), false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					if ((argscount <= 1))
					{
						return ((MoonSharp.Interpreter.Script)(obj)).RequireModule(((string)(pars[0])));
					}
					return ((MoonSharp.Interpreter.Script)(obj)).RequireModule(((string)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
				}
			}

			private sealed class M_e87066ffa4d2410884648dfd8b48ea0e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_e87066ffa4d2410884648dfd8b48ea0e()
				{
					this.Initialize("GetTypeMetatable", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(MoonSharp.Interpreter.DataType), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).GetTypeMetatable(((MoonSharp.Interpreter.DataType)(pars[0])));
				}
			}

			private sealed class M_cbb3b3b05859416bbed10068731597e3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_cbb3b3b05859416bbed10068731597e3()
				{
					this.Initialize("SetTypeMetatable", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("type", typeof(MoonSharp.Interpreter.DataType), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("metatable", typeof(MoonSharp.Interpreter.Table), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					((MoonSharp.Interpreter.Script)(obj)).SetTypeMetatable(((MoonSharp.Interpreter.DataType)(pars[0])), ((MoonSharp.Interpreter.Table)(pars[1])));
					return null;
				}
			}

			private sealed class M_6b129f8f58e5472bbaf37f351859b4d5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_6b129f8f58e5472bbaf37f351859b4d5()
				{
					this.Initialize("WarmUp", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					MoonSharp.Interpreter.Script.WarmUp();
					return null;
				}
			}

			private sealed class M_8922d4f9487e4ec3849188d8ffaa8a9c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_8922d4f9487e4ec3849188d8ffaa8a9c()
				{
					this.Initialize("CreateDynamicExpression", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).CreateDynamicExpression(((string)(pars[0])));
				}
			}

			private sealed class M_43ab32ba0bf84865a409a098d73c5ae9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_43ab32ba0bf84865a409a098d73c5ae9()
				{
					this.Initialize("CreateConstantDynamicExpression", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("code", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("constant", typeof(MoonSharp.Interpreter.DynValue), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).CreateConstantDynamicExpression(((string)(pars[0])), ((MoonSharp.Interpreter.DynValue)(pars[1])));
				}
			}

			private sealed class M_516a8a4cd0ac4f359001d999182bb2e8 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_516a8a4cd0ac4f359001d999182bb2e8()
				{
					this.Initialize("get_Registry", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Registry;
				}
			}

			private sealed class M_904e48f68ae640eaae4b4b57dfd815f5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_904e48f68ae640eaae4b4b57dfd815f5()
				{
					this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((object)(obj)).ToString();
				}
			}

			private sealed class M_c73c2a427b2544ffa000ff0b84363b9b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_c73c2a427b2544ffa000ff0b84363b9b()
				{
					this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(object), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((object)(obj)).Equals(((object)(pars[0])));
				}
			}

			private sealed class M_dba924bc2bc24f2cb9100c5354566c95 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_dba924bc2bc24f2cb9100c5354566c95()
				{
					this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((object)(obj)).GetHashCode();
				}
			}

			private sealed class M_71ba8a4297a94bd9bf3cbe05cd4a6b09 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal M_71ba8a4297a94bd9bf3cbe05cd4a6b09()
				{
					this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((object)(obj)).GetType();
				}
			}

			private sealed class P_b8b9640e05c5462cb3bc5a0715c8ead5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_b8b9640e05c5462cb3bc5a0715c8ead5() :
					base(typeof(MoonSharp.Interpreter.ScriptOptions), "DefaultOptions", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return MoonSharp.Interpreter.Script.DefaultOptions;
				}
			}

			private sealed class P_c7ddbdc1d468476381392c0962390924 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_c7ddbdc1d468476381392c0962390924() :
					base(typeof(MoonSharp.Interpreter.ScriptOptions), "Options", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Options;
				}
			}

			private sealed class P_45a1cf5169904bf690a200d6ccfdd64c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_45a1cf5169904bf690a200d6ccfdd64c() :
					base(typeof(MoonSharp.Interpreter.ScriptGlobalOptions), "GlobalOptions", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return MoonSharp.Interpreter.Script.GlobalOptions;
				}
			}

			private sealed class P_845a56b2b70e4e3aa780dc2c28679d9c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_845a56b2b70e4e3aa780dc2c28679d9c() :
					base(typeof(MoonSharp.Interpreter.Diagnostics.PerformanceStatistics), "PerformanceStats", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).PerformanceStats;
				}
			}

			private sealed class P_9004ba7d477746bfa582d82b5c88b282 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_9004ba7d477746bfa582d82b5c88b282() :
					base(typeof(MoonSharp.Interpreter.Table), "Globals", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Globals;
				}
			}

			private sealed class P_762a7898cbab4404871937e06970317a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_762a7898cbab4404871937e06970317a() :
					base(typeof(bool), "DebuggerEnabled", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(3)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).DebuggerEnabled;
				}

				protected override void SetValueImpl(MoonSharp.Interpreter.Script script, object obj, object value)
				{
					((MoonSharp.Interpreter.Script)(obj)).DebuggerEnabled = ((bool)(value));
				}
			}

			private sealed class P_ec50dada3aa94231bd511c7a7679e136 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_ec50dada3aa94231bd511c7a7679e136() :
					base(typeof(int), "SourceCodeCount", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).SourceCodeCount;
				}
			}

			private sealed class P_3327f505764b45aab1705dba88e499d5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal P_3327f505764b45aab1705dba88e499d5() :
					base(typeof(MoonSharp.Interpreter.Table), "Registry", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((MoonSharp.Interpreter.Script)(obj)).Registry;
				}
			}

			private sealed class F_1da771af519647b9a55aea146eabf20b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal F_1da771af519647b9a55aea146eabf20b() :
					base(typeof(string), "VERSION", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return MoonSharp.Interpreter.Script.VERSION;
				}
			}

			private sealed class F_c9b0fd6485c7431e8bb808039f675d6e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal F_c9b0fd6485c7431e8bb808039f675d6e() :
					base(typeof(string), "LUA_VERSION", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return MoonSharp.Interpreter.Script.LUA_VERSION;
				}
			}
		}
	}
}
