//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ----------------------------------------------------------
// Generated by MoonSharp.Hardwire v.1.0.5876.42281
// Compatible with MoonSharp v.1.99.999.9999 or equivalent
// ----------------------------------------------------------
// Code generated on 2016-02-02T23:29:25.7053234+01:00
// ----------------------------------------------------------
// 
// 
// 
namespace MyNamespace
{


	public abstract class MyClass
	{

		private MyClass()
		{
		}

		public static void Initialize()
		{
			MoonSharp.Interpreter.UserData.RegisterType(new TYPE_bac3cd69694d4e4bbe12106394b10aef());
			MoonSharp.Interpreter.UserData.RegisterType(new TYPE_ae5c1ee6490f403c965f79ad82aa6603());
		}

		#region Descriptor of MoonSharp.Interpreter.Interop.AnonWrapper
		// Descriptor of MoonSharp.Interpreter.Interop.AnonWrapper
		private sealed class TYPE_bac3cd69694d4e4bbe12106394b10aef : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor
		{

			internal TYPE_bac3cd69694d4e4bbe12106394b10aef() :
				base(typeof(MoonSharp.Interpreter.Interop.AnonWrapper))
			{
			}
		}
		#endregion

		#region Descriptor of System.TimeSpan
		// Descriptor of System.TimeSpan
		private sealed class TYPE_ae5c1ee6490f403c965f79ad82aa6603 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredUserDataDescriptor
		{

			internal TYPE_ae5c1ee6490f403c965f79ad82aa6603() :
				base(typeof(System.TimeSpan))
			{
				this.AddMember("__new", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("__new", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_235d66f4fdf8430ab1ddaf2bb1af4e7e(),
                                new MTHD_0bdb518f49664de6ae70e385aea15e7f(),
                                new MTHD_57fd732df3f94e83aa020029f391474e(),
                                new MTHD_9cf14054b9374894a9e2f68db3516e90(),
                                new VTDC_ab476a0bb01a4ad69f684b9cc5070f26()}));
				this.AddMember("get_Ticks", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Ticks", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_5ed0344944ea4cd89bbd1991f477b090()}));
				this.AddMember("get_Days", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Days", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_28a0962e1a094e6ebed901ab9303e0ee()}));
				this.AddMember("get_Hours", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Hours", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b4f6d98f49314a899b49525ef8219538()}));
				this.AddMember("get_Milliseconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Milliseconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_4008189be21241f49a386c440f240624()}));
				this.AddMember("get_Minutes", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Minutes", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_24429dfbbaa3400aa614253dc1fc8d0f()}));
				this.AddMember("get_Seconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_Seconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6d98c91542434575888f4f3234885387()}));
				this.AddMember("get_TotalDays", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_TotalDays", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_dd530796f7474b63827fc8a25658765b()}));
				this.AddMember("get_TotalHours", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_TotalHours", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_519ef9a501b74042ba7dbd1271afa97a()}));
				this.AddMember("get_TotalMilliseconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_TotalMilliseconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_c2b3b9f70fff468badb6fea99f1e86fb()}));
				this.AddMember("get_TotalMinutes", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_TotalMinutes", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ba22fafb0acb49dc945b5542a9483258()}));
				this.AddMember("get_TotalSeconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("get_TotalSeconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ef94e763ca2c458fa11b47de2a7ae9bb()}));
				this.AddMember("Add", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Add", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_122dc23f166f4c9b8668fa7c2d0f5ccc()}));
				this.AddMember("Compare", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Compare", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_86ca10bc92ff49d291907a42da71fdb4()}));
				this.AddMember("CompareTo", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("CompareTo", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cd781c00413942e78627632fc5a9d527(),
                                new MTHD_8ffbed85b8ef4e599d705989107e66c0()}));
				this.AddMember("FromDays", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromDays", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_2ae3628bbf354121b615ea759418ab3f()}));
				this.AddMember("Duration", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Duration", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_86d64667388949158e7f4eda4c50d793()}));
				this.AddMember("Equals", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Equals", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_d410858baa664288ae0874347ac92425(),
                                new MTHD_c876598606124a63a474d5705a942ff5(),
                                new MTHD_18b35391281f41caa650a4be5b7999c6()}));
				this.AddMember("GetHashCode", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetHashCode", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9535f0764eb04351aebc5b5eddc48b48()}));
				this.AddMember("FromHours", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromHours", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_cf5241c0461c4e929c7ea623f0b0f426()}));
				this.AddMember("FromMilliseconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromMilliseconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_57200d0315bc4a36b486f7f03b612629()}));
				this.AddMember("FromMinutes", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromMinutes", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_64c7fef3df65477ebcb8b0661f7f6b77()}));
				this.AddMember("Negate", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Negate", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7d9c085d05284faf9dcbe50e617a7709()}));
				this.AddMember("FromSeconds", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromSeconds", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_64d3422707644024b6199e9eb2713f06()}));
				this.AddMember("Subtract", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Subtract", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_60cef9c71ac647f584e71fe4ec157a1e()}));
				this.AddMember("FromTicks", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("FromTicks", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_6b938000a09d4794af5a97bf5abef0fa()}));
				this.AddMember("Parse", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("Parse", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_61c3207e0f744bb184b46a1e61877937(),
                                new MTHD_32b502b0fa274c04a708bea2e6d752cb()}));
				this.AddMember("ParseExact", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ParseExact", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b2397b27d9cd43b7ac1be0cb644a9984(),
                                new MTHD_19e8e0b178fc4424b70bf389c8a35fdb(),
                                new MTHD_7d9b9769a7e044a5b1572ac9f3fa7173(),
                                new MTHD_5de6fec2e3e94048859f89967e2e515c()}));
				this.AddMember("TryParse", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("TryParse", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_79ff03366e504e1999e92fbc591af94d(),
                                new MTHD_298f86e2ce8b4ae9839fce719ce55bc3()}));
				this.AddMember("TryParseExact", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("TryParseExact", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_acc10c326788417888b9dd5e1357f446(),
                                new MTHD_f2b26978534b427d95fc72630e63cb58(),
                                new MTHD_7c116075bd984dd296f1f9fc5fc408c5(),
                                new MTHD_9c2679dce9584e9f98495bd81723bae5()}));
				this.AddMember("ToString", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("ToString", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e0ac45b21d6541f9a5ddbeb97ec556a3(),
                                new MTHD_8266567f656e43c7a806cef7f8e1bac4(),
                                new MTHD_0037355c29cb47909f0342b82f7901b0()}));
				this.AddMember("op_UnaryNegation", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_UnaryNegation", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_f8dfe3a3057249398d8d71197fc9e40f()}));
				this.AddMember("op_Subtraction", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_Subtraction", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_30e3ca9518d04b609d6cc1c8b9bc9c04()}));
				this.AddMember("op_UnaryPlus", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_UnaryPlus", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_dc87950228624cdb9bf70ef0ef238fef()}));
				this.AddMember("op_Addition", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_Addition", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_ad55bd60e26343dcaa9dc1d251acaa71()}));
				this.AddMember("op_Equality", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_Equality", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_19b1a46aa1ef4f518c2b7a5ca031ebb4()}));
				this.AddMember("op_Inequality", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_Inequality", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_0b90c7daf4a84b9f8aa6e19abb0fe531()}));
				this.AddMember("op_LessThan", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_LessThan", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_a08ac9ddee964aa192a25a0bd9441e63()}));
				this.AddMember("op_LessThanOrEqual", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_LessThanOrEqual", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_7bbaa85c243b4dad9f4acaeebaffdead()}));
				this.AddMember("op_GreaterThan", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_GreaterThan", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_e99df15a85cf487aa2a0c210fe5857a4()}));
				this.AddMember("op_GreaterThanOrEqual", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("op_GreaterThanOrEqual", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_b3dcf18d25bb48dc8f78b7f3b9cade0f()}));
				this.AddMember("GetType", new MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor("GetType", typeof(System.TimeSpan), new MoonSharp.Interpreter.Interop.BasicDescriptors.IOverloadableMemberDescriptor[] {
                                new MTHD_9548a719dd1d428087a4c2c3c7a5c78c()}));
				this.AddMember("Ticks", new PROP_01fd68884e434a4c900289c7dba03537());
				this.AddMember("Days", new PROP_e84de1e8305346adb801197f7e6c1e05());
				this.AddMember("Hours", new PROP_180ceec155c842ddb2b8f8ab117fa596());
				this.AddMember("Milliseconds", new PROP_9fb4183e48ca4dc486598239d97bb84c());
				this.AddMember("Minutes", new PROP_1483647e215e4e369acd601a1c23a0a3());
				this.AddMember("Seconds", new PROP_72a58a7151c446439cd9161c59e182a1());
				this.AddMember("TotalDays", new PROP_8fdb119dee854f13b30c74b158c13837());
				this.AddMember("TotalHours", new PROP_7ace402a1f314627a53e131d7f3717c6());
				this.AddMember("TotalMilliseconds", new PROP_26b96c59bcda4dfba002a7b2914eae41());
				this.AddMember("TotalMinutes", new PROP_36943d55e1bd4fef945b9e23610361f7());
				this.AddMember("TotalSeconds", new PROP_a9fcbc76499145258f8b636f5e24d4ea());
				this.AddMember("Zero", new FLDV_aa70706e251746bb8e66d9a8459f7b33());
				this.AddMember("MaxValue", new FLDV_243c991cdc7e4dba971d91ce2226f35f());
				this.AddMember("MinValue", new FLDV_95582a00f0234fb688c9f6f36f5ae3f2());
				this.AddMember("TicksPerMillisecond", new FLDV_909bc5e813e840e99238f6a2d2c8f0bc());
				this.AddMember("TicksPerSecond", new FLDV_f609a5a27da94f4893241c06dce621ea());
				this.AddMember("TicksPerMinute", new FLDV_6667615320744ae1a1ad487d12a34de9());
				this.AddMember("TicksPerHour", new FLDV_c473204da79644dea7d32723cb5e25cc());
				this.AddMember("TicksPerDay", new FLDV_9ba4e68bce1249d383f51843eb620a45());
			}

			private sealed class MTHD_235d66f4fdf8430ab1ddaf2bb1af4e7e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_235d66f4fdf8430ab1ddaf2bb1af4e7e()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("ticks", typeof(long), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new System.TimeSpan(((long)(pars[0])));
				}
			}

			private sealed class MTHD_0bdb518f49664de6ae70e385aea15e7f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_0bdb518f49664de6ae70e385aea15e7f()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hours", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("minutes", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("seconds", typeof(int), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new System.TimeSpan(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])));
				}
			}

			private sealed class MTHD_57fd732df3f94e83aa020029f391474e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_57fd732df3f94e83aa020029f391474e()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("days", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hours", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("minutes", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("seconds", typeof(int), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new System.TimeSpan(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])), ((int)(pars[3])));
				}
			}

			private sealed class MTHD_9cf14054b9374894a9e2f68db3516e90 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_9cf14054b9374894a9e2f68db3516e90()
				{
					this.Initialize(".ctor", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("days", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("hours", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("minutes", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("seconds", typeof(int), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("milliseconds", typeof(int), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return new System.TimeSpan(((int)(pars[0])), ((int)(pars[1])), ((int)(pars[2])), ((int)(pars[3])), ((int)(pars[4])));
				}
			}

			#region Descriptor of
			// Descriptor of 
			private sealed class VTDC_ab476a0bb01a4ad69f684b9cc5070f26 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal VTDC_ab476a0bb01a4ad69f684b9cc5070f26() :
					base(typeof(void))
				{
					this.AddMember("__new", new MTHD_0a6590b2d78b4bb4a6802e9d27e5a4ff());
				}

				private sealed class MTHD_0a6590b2d78b4bb4a6802e9d27e5a4ff : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
				{

					internal MTHD_0a6590b2d78b4bb4a6802e9d27e5a4ff()
					{
						this.Initialize("__new", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
					}

					protected override object Invoke(object obj, object[] pars, int argscount)
					{
						return new System.TimeSpan();
					}
				}
			}
			#endregion

			private sealed class MTHD_5ed0344944ea4cd89bbd1991f477b090 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_5ed0344944ea4cd89bbd1991f477b090()
				{
					this.Initialize("get_Ticks", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Ticks;
				}
			}

			private sealed class MTHD_28a0962e1a094e6ebed901ab9303e0ee : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_28a0962e1a094e6ebed901ab9303e0ee()
				{
					this.Initialize("get_Days", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Days;
				}
			}

			private sealed class MTHD_b4f6d98f49314a899b49525ef8219538 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_b4f6d98f49314a899b49525ef8219538()
				{
					this.Initialize("get_Hours", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Hours;
				}
			}

			private sealed class MTHD_4008189be21241f49a386c440f240624 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_4008189be21241f49a386c440f240624()
				{
					this.Initialize("get_Milliseconds", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Milliseconds;
				}
			}

			private sealed class MTHD_24429dfbbaa3400aa614253dc1fc8d0f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_24429dfbbaa3400aa614253dc1fc8d0f()
				{
					this.Initialize("get_Minutes", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Minutes;
				}
			}

			private sealed class MTHD_6d98c91542434575888f4f3234885387 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_6d98c91542434575888f4f3234885387()
				{
					this.Initialize("get_Seconds", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Seconds;
				}
			}

			private sealed class MTHD_dd530796f7474b63827fc8a25658765b : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_dd530796f7474b63827fc8a25658765b()
				{
					this.Initialize("get_TotalDays", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).TotalDays;
				}
			}

			private sealed class MTHD_519ef9a501b74042ba7dbd1271afa97a : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_519ef9a501b74042ba7dbd1271afa97a()
				{
					this.Initialize("get_TotalHours", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).TotalHours;
				}
			}

			private sealed class MTHD_c2b3b9f70fff468badb6fea99f1e86fb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_c2b3b9f70fff468badb6fea99f1e86fb()
				{
					this.Initialize("get_TotalMilliseconds", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).TotalMilliseconds;
				}
			}

			private sealed class MTHD_ba22fafb0acb49dc945b5542a9483258 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_ba22fafb0acb49dc945b5542a9483258()
				{
					this.Initialize("get_TotalMinutes", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).TotalMinutes;
				}
			}

			private sealed class MTHD_ef94e763ca2c458fa11b47de2a7ae9bb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_ef94e763ca2c458fa11b47de2a7ae9bb()
				{
					this.Initialize("get_TotalSeconds", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).TotalSeconds;
				}
			}

			private sealed class MTHD_122dc23f166f4c9b8668fa7c2d0f5ccc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_122dc23f166f4c9b8668fa7c2d0f5ccc()
				{
					this.Initialize("Add", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("ts", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Add(((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_86ca10bc92ff49d291907a42da71fdb4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_86ca10bc92ff49d291907a42da71fdb4()
				{
					this.Initialize("Compare", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.Compare(((System.TimeSpan)(pars[0])), ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_cd781c00413942e78627632fc5a9d527 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_cd781c00413942e78627632fc5a9d527()
				{
					this.Initialize("CompareTo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(object), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).CompareTo(((object)(pars[0])));
				}
			}

			private sealed class MTHD_8ffbed85b8ef4e599d705989107e66c0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_8ffbed85b8ef4e599d705989107e66c0()
				{
					this.Initialize("CompareTo", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).CompareTo(((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_2ae3628bbf354121b615ea759418ab3f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_2ae3628bbf354121b615ea759418ab3f()
				{
					this.Initialize("FromDays", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(double), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromDays(((double)(pars[0])));
				}
			}

			private sealed class MTHD_86d64667388949158e7f4eda4c50d793 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_86d64667388949158e7f4eda4c50d793()
				{
					this.Initialize("Duration", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Duration();
				}
			}

			private sealed class MTHD_d410858baa664288ae0874347ac92425 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_d410858baa664288ae0874347ac92425()
				{
					this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(object), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Equals(((object)(pars[0])));
				}
			}

			private sealed class MTHD_c876598606124a63a474d5705a942ff5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_c876598606124a63a474d5705a942ff5()
				{
					this.Initialize("Equals", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("obj", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Equals(((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_18b35391281f41caa650a4be5b7999c6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_18b35391281f41caa650a4be5b7999c6()
				{
					this.Initialize("Equals", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.Equals(((System.TimeSpan)(pars[0])), ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_9535f0764eb04351aebc5b5eddc48b48 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_9535f0764eb04351aebc5b5eddc48b48()
				{
					this.Initialize("GetHashCode", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).GetHashCode();
				}
			}

			private sealed class MTHD_cf5241c0461c4e929c7ea623f0b0f426 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_cf5241c0461c4e929c7ea623f0b0f426()
				{
					this.Initialize("FromHours", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(double), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromHours(((double)(pars[0])));
				}
			}

			private sealed class MTHD_57200d0315bc4a36b486f7f03b612629 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_57200d0315bc4a36b486f7f03b612629()
				{
					this.Initialize("FromMilliseconds", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(double), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromMilliseconds(((double)(pars[0])));
				}
			}

			private sealed class MTHD_64c7fef3df65477ebcb8b0661f7f6b77 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_64c7fef3df65477ebcb8b0661f7f6b77()
				{
					this.Initialize("FromMinutes", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(double), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromMinutes(((double)(pars[0])));
				}
			}

			private sealed class MTHD_7d9c085d05284faf9dcbe50e617a7709 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_7d9c085d05284faf9dcbe50e617a7709()
				{
					this.Initialize("Negate", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Negate();
				}
			}

			private sealed class MTHD_64d3422707644024b6199e9eb2713f06 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_64d3422707644024b6199e9eb2713f06()
				{
					this.Initialize("FromSeconds", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(double), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromSeconds(((double)(pars[0])));
				}
			}

			private sealed class MTHD_60cef9c71ac647f584e71fe4ec157a1e : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_60cef9c71ac647f584e71fe4ec157a1e()
				{
					this.Initialize("Subtract", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("ts", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).Subtract(((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_6b938000a09d4794af5a97bf5abef0fa : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_6b938000a09d4794af5a97bf5abef0fa()
				{
					this.Initialize("FromTicks", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("value", typeof(long), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.FromTicks(((long)(pars[0])));
				}
			}

			private sealed class MTHD_61c3207e0f744bb184b46a1e61877937 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_61c3207e0f744bb184b46a1e61877937()
				{
					this.Initialize("Parse", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("s", typeof(string), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.Parse(((string)(pars[0])));
				}
			}

			private sealed class MTHD_32b502b0fa274c04a708bea2e6d752cb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_32b502b0fa274c04a708bea2e6d752cb()
				{
					this.Initialize("Parse", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.Parse(((string)(pars[0])), ((System.IFormatProvider)(pars[1])));
				}
			}

			private sealed class MTHD_b2397b27d9cd43b7ac1be0cb644a9984 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_b2397b27d9cd43b7ac1be0cb644a9984()
				{
					this.Initialize("ParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.ParseExact(((string)(pars[0])), ((string)(pars[1])), ((System.IFormatProvider)(pars[2])));
				}
			}

			private sealed class MTHD_19e8e0b178fc4424b70bf389c8a35fdb : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_19e8e0b178fc4424b70bf389c8a35fdb()
				{
					this.Initialize("ParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formats", typeof(string[]), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.ParseExact(((string)(pars[0])), ((string[])(pars[1])), ((System.IFormatProvider)(pars[2])));
				}
			}

			private sealed class MTHD_7d9b9769a7e044a5b1572ac9f3fa7173 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_7d9b9769a7e044a5b1572ac9f3fa7173()
				{
					this.Initialize("ParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("styles", typeof(System.Globalization.TimeSpanStyles), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.ParseExact(((string)(pars[0])), ((string)(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.Globalization.TimeSpanStyles)(pars[3])));
				}
			}

			private sealed class MTHD_5de6fec2e3e94048859f89967e2e515c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_5de6fec2e3e94048859f89967e2e515c()
				{
					this.Initialize("ParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formats", typeof(string[]), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("styles", typeof(System.Globalization.TimeSpanStyles), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.ParseExact(((string)(pars[0])), ((string[])(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.Globalization.TimeSpanStyles)(pars[3])));
				}
			}

			private sealed class MTHD_79ff03366e504e1999e92fbc591af94d : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_79ff03366e504e1999e92fbc591af94d()
				{
					this.Initialize("TryParse", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("s", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParse(((string)(pars[0])), ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_298f86e2ce8b4ae9839fce719ce55bc3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_298f86e2ce8b4ae9839fce719ce55bc3()
				{
					this.Initialize("TryParse", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParse(((string)(pars[0])), ((System.IFormatProvider)(pars[1])), ((System.TimeSpan)(pars[2])));
				}
			}

			private sealed class MTHD_acc10c326788417888b9dd5e1357f446 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_acc10c326788417888b9dd5e1357f446()
				{
					this.Initialize("TryParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParseExact(((string)(pars[0])), ((string)(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.TimeSpan)(pars[3])));
				}
			}

			private sealed class MTHD_f2b26978534b427d95fc72630e63cb58 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_f2b26978534b427d95fc72630e63cb58()
				{
					this.Initialize("TryParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formats", typeof(string[]), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParseExact(((string)(pars[0])), ((string[])(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.TimeSpan)(pars[3])));
				}
			}

			private sealed class MTHD_7c116075bd984dd296f1f9fc5fc408c5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_7c116075bd984dd296f1f9fc5fc408c5()
				{
					this.Initialize("TryParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("styles", typeof(System.Globalization.TimeSpanStyles), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParseExact(((string)(pars[0])), ((string)(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.Globalization.TimeSpanStyles)(pars[3])), ((System.TimeSpan)(pars[4])));
				}
			}

			private sealed class MTHD_9c2679dce9584e9f98495bd81723bae5 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_9c2679dce9584e9f98495bd81723bae5()
				{
					this.Initialize("TryParseExact", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("input", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formats", typeof(string[]), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("styles", typeof(System.Globalization.TimeSpanStyles), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("result", typeof(System.TimeSpan), false, null, true, true, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return System.TimeSpan.TryParseExact(((string)(pars[0])), ((string[])(pars[1])), ((System.IFormatProvider)(pars[2])), ((System.Globalization.TimeSpanStyles)(pars[3])), ((System.TimeSpan)(pars[4])));
				}
			}

			private sealed class MTHD_e0ac45b21d6541f9a5ddbeb97ec556a3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_e0ac45b21d6541f9a5ddbeb97ec556a3()
				{
					this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).ToString();
				}
			}

			private sealed class MTHD_8266567f656e43c7a806cef7f8e1bac4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_8266567f656e43c7a806cef7f8e1bac4()
				{
					this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).ToString(((string)(pars[0])));
				}
			}

			private sealed class MTHD_0037355c29cb47909f0342b82f7901b0 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_0037355c29cb47909f0342b82f7901b0()
				{
					this.Initialize("ToString", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("format", typeof(string), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("formatProvider", typeof(System.IFormatProvider), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((System.TimeSpan)(obj)).ToString(((string)(pars[0])), ((System.IFormatProvider)(pars[1])));
				}
			}

			private sealed class MTHD_f8dfe3a3057249398d8d71197fc9e40f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_f8dfe3a3057249398d8d71197fc9e40f()
				{
					this.Initialize("op_UnaryNegation", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (-((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_30e3ca9518d04b609d6cc1c8b9bc9c04 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_30e3ca9518d04b609d6cc1c8b9bc9c04()
				{
					this.Initialize("op_Subtraction", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) - ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_dc87950228624cdb9bf70ef0ef238fef : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_dc87950228624cdb9bf70ef0ef238fef()
				{
					this.Initialize("op_UnaryPlus", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (+((System.TimeSpan)(pars[0])));
				}
			}

			private sealed class MTHD_ad55bd60e26343dcaa9dc1d251acaa71 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_ad55bd60e26343dcaa9dc1d251acaa71()
				{
					this.Initialize("op_Addition", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) + ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_19b1a46aa1ef4f518c2b7a5ca031ebb4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_19b1a46aa1ef4f518c2b7a5ca031ebb4()
				{
					this.Initialize("op_Equality", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) == ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_0b90c7daf4a84b9f8aa6e19abb0fe531 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_0b90c7daf4a84b9f8aa6e19abb0fe531()
				{
					this.Initialize("op_Inequality", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) != ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_a08ac9ddee964aa192a25a0bd9441e63 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_a08ac9ddee964aa192a25a0bd9441e63()
				{
					this.Initialize("op_LessThan", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) < ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_7bbaa85c243b4dad9f4acaeebaffdead : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_7bbaa85c243b4dad9f4acaeebaffdead()
				{
					this.Initialize("op_LessThanOrEqual", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) <= ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_e99df15a85cf487aa2a0c210fe5857a4 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_e99df15a85cf487aa2a0c210fe5857a4()
				{
					this.Initialize("op_GreaterThan", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) > ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_b3dcf18d25bb48dc8f78b7f3b9cade0f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_b3dcf18d25bb48dc8f78b7f3b9cade0f()
				{
					this.Initialize("op_GreaterThanOrEqual", true, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[] {
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t1", typeof(System.TimeSpan), false, null, false, false, false),
                                new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor("t2", typeof(System.TimeSpan), false, null, false, false, false)}, false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return (((System.TimeSpan)(pars[0])) >= ((System.TimeSpan)(pars[1])));
				}
			}

			private sealed class MTHD_9548a719dd1d428087a4c2c3c7a5c78c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMethodMemberDescriptor
			{

				internal MTHD_9548a719dd1d428087a4c2c3c7a5c78c()
				{
					this.Initialize("GetType", false, new MoonSharp.Interpreter.Interop.BasicDescriptors.ParameterDescriptor[0], false);
				}

				protected override object Invoke(object obj, object[] pars, int argscount)
				{
					return ((object)(obj)).GetType();
				}
			}

			private sealed class PROP_01fd68884e434a4c900289c7dba03537 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_01fd68884e434a4c900289c7dba03537() :
					base(typeof(long), "Ticks", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Ticks;
				}
			}

			private sealed class PROP_e84de1e8305346adb801197f7e6c1e05 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_e84de1e8305346adb801197f7e6c1e05() :
					base(typeof(int), "Days", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Days;
				}
			}

			private sealed class PROP_180ceec155c842ddb2b8f8ab117fa596 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_180ceec155c842ddb2b8f8ab117fa596() :
					base(typeof(int), "Hours", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Hours;
				}
			}

			private sealed class PROP_9fb4183e48ca4dc486598239d97bb84c : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_9fb4183e48ca4dc486598239d97bb84c() :
					base(typeof(int), "Milliseconds", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Milliseconds;
				}
			}

			private sealed class PROP_1483647e215e4e369acd601a1c23a0a3 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_1483647e215e4e369acd601a1c23a0a3() :
					base(typeof(int), "Minutes", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Minutes;
				}
			}

			private sealed class PROP_72a58a7151c446439cd9161c59e182a1 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_72a58a7151c446439cd9161c59e182a1() :
					base(typeof(int), "Seconds", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).Seconds;
				}
			}

			private sealed class PROP_8fdb119dee854f13b30c74b158c13837 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_8fdb119dee854f13b30c74b158c13837() :
					base(typeof(double), "TotalDays", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).TotalDays;
				}
			}

			private sealed class PROP_7ace402a1f314627a53e131d7f3717c6 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_7ace402a1f314627a53e131d7f3717c6() :
					base(typeof(double), "TotalHours", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).TotalHours;
				}
			}

			private sealed class PROP_26b96c59bcda4dfba002a7b2914eae41 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_26b96c59bcda4dfba002a7b2914eae41() :
					base(typeof(double), "TotalMilliseconds", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).TotalMilliseconds;
				}
			}

			private sealed class PROP_36943d55e1bd4fef945b9e23610361f7 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_36943d55e1bd4fef945b9e23610361f7() :
					base(typeof(double), "TotalMinutes", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).TotalMinutes;
				}
			}

			private sealed class PROP_a9fcbc76499145258f8b636f5e24d4ea : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal PROP_a9fcbc76499145258f8b636f5e24d4ea() :
					base(typeof(double), "TotalSeconds", false, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return ((System.TimeSpan)(obj)).TotalSeconds;
				}
			}

			private sealed class FLDV_aa70706e251746bb8e66d9a8459f7b33 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_aa70706e251746bb8e66d9a8459f7b33() :
					base(typeof(System.TimeSpan), "Zero", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.Zero;
				}
			}

			private sealed class FLDV_243c991cdc7e4dba971d91ce2226f35f : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_243c991cdc7e4dba971d91ce2226f35f() :
					base(typeof(System.TimeSpan), "MaxValue", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.MaxValue;
				}
			}

			private sealed class FLDV_95582a00f0234fb688c9f6f36f5ae3f2 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_95582a00f0234fb688c9f6f36f5ae3f2() :
					base(typeof(System.TimeSpan), "MinValue", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.MinValue;
				}
			}

			private sealed class FLDV_909bc5e813e840e99238f6a2d2c8f0bc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_909bc5e813e840e99238f6a2d2c8f0bc() :
					base(typeof(long), "TicksPerMillisecond", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.TicksPerMillisecond;
				}
			}

			private sealed class FLDV_f609a5a27da94f4893241c06dce621ea : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_f609a5a27da94f4893241c06dce621ea() :
					base(typeof(long), "TicksPerSecond", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.TicksPerSecond;
				}
			}

			private sealed class FLDV_6667615320744ae1a1ad487d12a34de9 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_6667615320744ae1a1ad487d12a34de9() :
					base(typeof(long), "TicksPerMinute", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.TicksPerMinute;
				}
			}

			private sealed class FLDV_c473204da79644dea7d32723cb5e25cc : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_c473204da79644dea7d32723cb5e25cc() :
					base(typeof(long), "TicksPerHour", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.TicksPerHour;
				}
			}

			private sealed class FLDV_9ba4e68bce1249d383f51843eb620a45 : MoonSharp.Interpreter.Interop.StandardDescriptors.HardwiredDescriptors.HardwiredMemberDescriptor
			{

				internal FLDV_9ba4e68bce1249d383f51843eb620a45() :
					base(typeof(long), "TicksPerDay", true, ((MoonSharp.Interpreter.Interop.BasicDescriptors.MemberDescriptorAccess)(1)))
				{
				}

				protected override object GetValueImpl(MoonSharp.Interpreter.Script script, object obj)
				{
					return System.TimeSpan.TicksPerDay;
				}
			}
		}
		#endregion
	}
}
